### PR TITLE
ITensorMPS update

### PR DESCRIPTION
**Pull request by emstoudenmire**
- Add ITensorMPS as a test dependency
- Add `using ITensorMPS` to certain examples

### CODE REVIEW

**Comment by emstoudenmire** [comment]
It seems the CI here thinks that `ITensorMPS` is not yet registered: `"ERROR: expected package `ITensorMPS [0d1a4710]` to be registered."` I checked that the hash in Project.toml is correct.

**Comment by mtfishman** [comment]
It may be an issue with the CI configuration. Sometimes the registry doesn't get updated properly.

**Comment by mtfishman** [comment]
Very likely the CI script is not configured correctly. Here are some references for CI scripts for GLMakie:
https://github.com/MakieOrg/Makie.jl/blob/746b03f46282f2385d438b01b486a74ea10f023d/.github/workflows/reference_tests.yml#L67-L117
https://github.com/JuliaPlots/GLMakie.jl/blob/f6e4d59f7170ff002c0c12016fdacee0c4b19cc7/.github/workflows/ci.yml

**Comment by mtfishman** [comment]
@emstoudenmire looks like I got the workflow working, based on trying to match the [GLMakie.jl CI workflow](https://github.com/MakieOrg/Makie.jl/blob/746b03f46282f2385d438b01b486a74ea10f023d/.github/workflows/reference_tests.yml#L67-L117) as closely as possible.

I think the solution to the issue of not finding `ITensorMPS.jl` was forcing an update of the registry and then packages with: `Pkg.Registry.update(); Pkg.update()`.

**Comment by emstoudenmire** [comment]
Great, thanks for taking a look at that & figuring it out.

**Pull request merged**
